%Read level1 residual fields
file2d = 'BiscayLevel1Residual.nc';
u = nc_varget(file2d,'Vel_X');
v = nc_varget(file2d,'Vel_Y');
lon = nc_varget(file2d,'lon');
lat = nc_varget(file2d, 'lat');
level = nc_varget(file2d, 'Lev_Z');

%Create level1 residual fields
out2d = 'MOHIDresidual2D.nc';
nc_create_empty(out2d, nc_write_mode);
nc_add_dimension(out2d, 'lon', length(lon));
nc_add_dimension(out2d, 'lat', length(lat));

s_ncvars = struct ( 'Name', ...
                        {   'lon',...
                            'lat',...
                            'u',...
                            'v',...
                            'elevation'}, ...
                   'Nctype', ...
                        {   'float',...
                            'float',...
                            'float',...
                            'float',...
                            'float'}, ...
                   'Dimension', ...
                        {   {'lon'},...
                            {'lat'},...
                            {'lat' 'lon'},...
                            {'lat' 'lon'},...
                            {'lat' 'lon'}}, ...
                   'Attribute', ...
                        {   struct( 'Name','units',...
                                    'Value','degrees_east' ), ...
                            struct( 'Name','units',...
                                    'Value','degrees_north' ), ...
                            struct( 'Name','units',...
                                    'Value','m s-1' ), ...
                            struct( 'Name','units',...
                                    'Value','m s-1' ), ...
                            struct( 'Name','units',...
                                    'Value','m' ), ...
                         })

for i=1:length(s_ncvars)                     
    nc_addvar(out2d, s_ncvars(i));
end

nc_dump(out2d);